services:
  debtools:
    build:
      context: .
      dockerfile: Dockerfile.debtools
    image: cockpit-authelia-users-debtools:latest
    volumes:
      - ../:/workspace
    working_dir: /workspace
